package com.txy.gkzyfz.test;

import com.txy.gkzyfz.test.Huiyuan;

public interface HuiyuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int deleteByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int insert(Huiyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int insertSelective(Huiyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    Huiyuan selectByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int updateByPrimaryKeySelective(Huiyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int updateByPrimaryKey(Huiyuan record);
}