package com.txy.gkzyfz.test;

import com.txy.gkzyfz.test.Xuexiao;

public interface XuexiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int deleteByPrimaryKey(Integer xid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int insert(Xuexiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int insertSelective(Xuexiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    Xuexiao selectByPrimaryKey(Integer xid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int updateByPrimaryKeySelective(Xuexiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    int updateByPrimaryKey(Xuexiao record);
}