package com.txy.gkzyfz.test;

public class Xuexiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xid
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private Integer xid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xname
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private String xname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xdiqu
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private String xdiqu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xleixing
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private String xleixing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xlike
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private String xlike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xwenke
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private String xwenke;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xllow
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private Integer xllow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xlhigh
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private Integer xlhigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xwlow
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private Integer xwlow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuexiao.xwhigh
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    private Integer xwhigh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xid
     *
     * @return the value of xuexiao.xid
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public Integer getXid() {
        return xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xid
     *
     * @param xid the value for xuexiao.xid
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXid(Integer xid) {
        this.xid = xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xname
     *
     * @return the value of xuexiao.xname
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public String getXname() {
        return xname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xname
     *
     * @param xname the value for xuexiao.xname
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXname(String xname) {
        this.xname = xname == null ? null : xname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xdiqu
     *
     * @return the value of xuexiao.xdiqu
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public String getXdiqu() {
        return xdiqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xdiqu
     *
     * @param xdiqu the value for xuexiao.xdiqu
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXdiqu(String xdiqu) {
        this.xdiqu = xdiqu == null ? null : xdiqu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xleixing
     *
     * @return the value of xuexiao.xleixing
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public String getXleixing() {
        return xleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xleixing
     *
     * @param xleixing the value for xuexiao.xleixing
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXleixing(String xleixing) {
        this.xleixing = xleixing == null ? null : xleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xlike
     *
     * @return the value of xuexiao.xlike
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public String getXlike() {
        return xlike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xlike
     *
     * @param xlike the value for xuexiao.xlike
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXlike(String xlike) {
        this.xlike = xlike == null ? null : xlike.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xwenke
     *
     * @return the value of xuexiao.xwenke
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public String getXwenke() {
        return xwenke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xwenke
     *
     * @param xwenke the value for xuexiao.xwenke
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXwenke(String xwenke) {
        this.xwenke = xwenke == null ? null : xwenke.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xllow
     *
     * @return the value of xuexiao.xllow
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public Integer getXllow() {
        return xllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xllow
     *
     * @param xllow the value for xuexiao.xllow
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXllow(Integer xllow) {
        this.xllow = xllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xlhigh
     *
     * @return the value of xuexiao.xlhigh
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public Integer getXlhigh() {
        return xlhigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xlhigh
     *
     * @param xlhigh the value for xuexiao.xlhigh
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXlhigh(Integer xlhigh) {
        this.xlhigh = xlhigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xwlow
     *
     * @return the value of xuexiao.xwlow
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public Integer getXwlow() {
        return xwlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xwlow
     *
     * @param xwlow the value for xuexiao.xwlow
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXwlow(Integer xwlow) {
        this.xwlow = xwlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuexiao.xwhigh
     *
     * @return the value of xuexiao.xwhigh
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public Integer getXwhigh() {
        return xwhigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuexiao.xwhigh
     *
     * @param xwhigh the value for xuexiao.xwhigh
     *
     * @mbg.generated Sun Apr 19 22:54:29 CST 2020
     */
    public void setXwhigh(Integer xwhigh) {
        this.xwhigh = xwhigh;
    }
}