package com.txy.gkzyfz.pojo;

public class Guanliyuan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.gid
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.gname
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.gusername
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String gusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.gpassword
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String gpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.gid
     *
     * @return the value of guanliyuan.gid
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.gid
     *
     * @param gid the value for guanliyuan.gid
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.gname
     *
     * @return the value of guanliyuan.gname
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.gname
     *
     * @param gname the value for guanliyuan.gname
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.gusername
     *
     * @return the value of guanliyuan.gusername
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getGusername() {
        return gusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.gusername
     *
     * @param gusername the value for guanliyuan.gusername
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setGusername(String gusername) {
        this.gusername = gusername == null ? null : gusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.gpassword
     *
     * @return the value of guanliyuan.gpassword
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getGpassword() {
        return gpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.gpassword
     *
     * @param gpassword the value for guanliyuan.gpassword
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setGpassword(String gpassword) {
        this.gpassword = gpassword == null ? null : gpassword.trim();
    }
}