package com.txy.gkzyfz.pojo;

public class Huiyuan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huiyuan.hid
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huiyuan.hname
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String hname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huiyuan.husername
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String husername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huiyuan.hpassword
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String hpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huiyuan.hwenli
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private String hwenli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huiyuan.hfenshu
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    private Integer hfenshu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huiyuan.hid
     *
     * @return the value of huiyuan.hid
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huiyuan.hid
     *
     * @param hid the value for huiyuan.hid
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setHid(String hid) {
        this.hid = hid == null ? null : hid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huiyuan.hname
     *
     * @return the value of huiyuan.hname
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huiyuan.hname
     *
     * @param hname the value for huiyuan.hname
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setHname(String hname) {
        this.hname = hname == null ? null : hname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huiyuan.husername
     *
     * @return the value of huiyuan.husername
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getHusername() {
        return husername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huiyuan.husername
     *
     * @param husername the value for huiyuan.husername
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setHusername(String husername) {
        this.husername = husername == null ? null : husername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huiyuan.hpassword
     *
     * @return the value of huiyuan.hpassword
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getHpassword() {
        return hpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huiyuan.hpassword
     *
     * @param hpassword the value for huiyuan.hpassword
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setHpassword(String hpassword) {
        this.hpassword = hpassword == null ? null : hpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huiyuan.hwenli
     *
     * @return the value of huiyuan.hwenli
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public String getHwenli() {
        return hwenli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huiyuan.hwenli
     *
     * @param hwenli the value for huiyuan.hwenli
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setHwenli(String hwenli) {
        this.hwenli = hwenli == null ? null : hwenli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huiyuan.hfenshu
     *
     * @return the value of huiyuan.hfenshu
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public Integer getHfenshu() {
        return hfenshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huiyuan.hfenshu
     *
     * @param hfenshu the value for huiyuan.hfenshu
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    public void setHfenshu(Integer hfenshu) {
        this.hfenshu = hfenshu;
    }
}