package com.txy.gkzyfz.pojo;

import com.txy.gkzyfz.pojo.Huiyuan;

public interface HuiyuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int deleteByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int insert(Huiyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int insertSelective(Huiyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    Huiyuan selectByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int updateByPrimaryKeySelective(Huiyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huiyuan
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int updateByPrimaryKey(Huiyuan record);

    Huiyuan selectByUsername(String username);
}