package com.txy.gkzyfz.pojo;

import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

public interface XuexiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int deleteByPrimaryKey(Integer xid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int insert(Xuexiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int insertSelective(Xuexiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    Xuexiao selectByPrimaryKey(Integer xid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int updateByPrimaryKeySelective(Xuexiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuexiao
     *
     * @mbg.generated Fri Apr 17 08:46:39 CST 2020
     */
    int updateByPrimaryKey(Xuexiao record);

    List<Xuexiao> selectXuexiao();
    List<Xuexiao> selectByName(String name);
    List<Xuexiao> selectByDiqu(String diqu);
    List<Xuexiao> selectByLeixing(String leixing);
    List<Xuexiao> selectByWenfen(Integer wenfen);
    List<Xuexiao> selectByLifen(Integer lifen);

    List<Xuexiao> selectZhongdian();
    List<Xuexiao> selectQita();
    List<Xuexiao> selectPutong();

    List<Xuexiao> selectXuexiaoOrderDiqu();

    List<Xuexiao> selectByNameGD(String name);

    List<Xuexiao> selectByDiquGD(String diqu);

    List<Xuexiao> selectByWenfenGD(Integer wenfen);

    List<Xuexiao> selectByLifenGD(Integer lifen);

    List<Xuexiao> selectByNameQT(String name);

    List<Xuexiao> selectByDiquQT(String diqu);

    List<Xuexiao> selectByWenfenQT(Integer wenfen);

    List<Xuexiao> selectByLifenQT(Integer lifen);

    List<Xuexiao> selectByNamePT(String name);

    List<Xuexiao> selectByDiquPT(String diqu);

    List<Xuexiao> selectByWenfenPT(Integer wenfen);

    List<Xuexiao> selectByLifenPT(Integer lifen);
}